/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.Banco;
import dao.ManipularImagem;
import dao.Proprietario;
import dao.Veiculo;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Paulo
 */
public class CadastroVeiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroV
     */
    public CadastroVeiculo() {
        initComponents();
    }
    BufferedImage imagem;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblCor = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        campoModelo = new javax.swing.JTextField();
        campoMarca = new javax.swing.JTextField();
        campoCor = new javax.swing.JTextField();
        campoPlaca = new javax.swing.JTextField();
        btnSelecionar = new javax.swing.JButton();
        lblCPF = new javax.swing.JLabel();
        campoCPF = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        campoID = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("Cadastro de veiculos");

        lblModelo.setText("Modelo:");

        lblMarca.setText("Marca:");

        lblCor.setText("Cor:");

        lblPlaca.setText("Placa:");

        btnSelecionar.setText("Selecione a imagem");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        lblCPF.setText("CPF:");

        jToggleButton1.setText("Cadastrar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Alterar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Excluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jToggleButton1)
                .addContainerGap(398, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 43, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(lblModelo)
                            .addGap(2, 2, 2)
                            .addComponent(campoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(lblMarca)
                            .addGap(7, 7, 7)
                            .addComponent(campoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(lblCor)
                            .addGap(19, 19, 19)
                            .addComponent(campoCor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPlaca)
                                .addComponent(lblCPF))
                            .addGap(11, 11, 11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(100, 100, 100)
                            .addComponent(btnSelecionar))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnBuscar))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(jToggleButton2)
                            .addGap(25, 25, 25)
                            .addComponent(jButton1)
                            .addGap(17, 17, 17)
                            .addComponent(jButton3)))
                    .addGap(0, 44, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(331, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(52, 52, 52))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 50, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(25, 25, 25)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblModelo)
                        .addComponent(campoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblMarca)
                        .addComponent(campoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCor)
                        .addComponent(campoCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPlaca)
                            .addGap(16, 16, 16)
                            .addComponent(lblCPF))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(campoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btnSelecionar)))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar))
                    .addGap(67, 67, 67)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jToggleButton2)
                        .addComponent(jButton1)
                        .addComponent(jButton3))
                    .addGap(0, 50, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       
       Banco dao = new Banco();
       Proprietario veiculo = new Proprietario(); 
       veiculo.setCpf(campoCPF.getText());
       veiculo = dao.busca(veiculo);
       if(veiculo.getIdProprietario()== 0)
       {
            JOptionPane.showMessageDialog(rootPane, "CPF inválido!");
           
       }
       else
       {
          String insert = "INSERT into cadveiculo (idprop_veic,placa_veic, modelo_veic,  marca_veic,cor_veic, imagem_veic) values ("
            +veiculo.getIdProprietario()+",'"+campoPlaca.getText()+"','"+campoModelo.getText()+"','"
                  +campoMarca.getText()+"','"+campoCor.getText()+"',?)";
       
            if(dao.cadVeic(insert,ManipularImagem.getImgBytes(imagem)))
            {
                
                campoPlaca.setText("");
                campoID.setText("");
                campoModelo.setText("");
                campoMarca.setText("");
                campoCor.setText("");
                jLabel1.setIcon(new ImageIcon());
                campoCPF.setText("");
                JOptionPane.showMessageDialog(rootPane, "Cadastro concluido com sucesso!");

            }
             else
             {
                 JOptionPane.showMessageDialog(rootPane, "Cadastro não enviado!");
             }  
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        JFileChooser fc = new JFileChooser();
        int res = fc.showOpenDialog(null);

        if (res == JFileChooser.APPROVE_OPTION) {
            File arquivo = fc.getSelectedFile();

            try {
                imagem = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(), 160, 160);

                jLabel1.setIcon(new ImageIcon(imagem));

            } catch (Exception ex) {
               // System.out.println(ex.printStackTrace().toString());
            }

        } else {
            JOptionPane.showMessageDialog(null, "Voce nao selecionou nenhum arquivo.");
        }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        
        Banco dao = new Banco();
        Proprietario veiculo = new Proprietario();
        veiculo.setCpf(campoCPF.getText());
        veiculo = dao.busca(veiculo);
       
        
        
         if(veiculo.getIdProprietario()== 0)
       {
            JOptionPane.showMessageDialog(rootPane, "CPF inválido!");
           
       }
       else
       {
           String sql = "UPDATE cadveiculo set  idprop_veic = '"
                +veiculo.getIdProprietario()+"', placa_veic ='"+campoPlaca.getText()+"', modelo_veic ='"
                +campoModelo.getText()+"', marca_veic = '"
                +campoMarca.getText()+"', cor_veic ='"+campoCor.getText()+"' where id_veic = "
                +Integer.parseInt(campoID.getText());
       
            if(dao.inserir(sql))
            {
                 
                campoPlaca.setText("");
                campoID.setText("");
                campoModelo.setText("");
                campoMarca.setText("");
                campoCor.setText("");
                jLabel1.setIcon(new ImageIcon());
                campoCPF.setText("");
                JOptionPane.showMessageDialog(rootPane, "Cadastro alterado com sucesso!");

            }
             else
             {
                 JOptionPane.showMessageDialog(rootPane, "Cadastro não alterado!");

             }  
       }
         
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        Banco dao = new Banco();
        String sql= "DELETE from cadveiculo where id_veic =" +Integer.parseInt(campoID.getText());
        if(dao.inserir(sql))
        {
            campoPlaca.setText("");
            campoID.setText("");
            campoModelo.setText("");
            campoMarca.setText("");
            campoCor.setText("");
            jLabel1.setIcon(new ImageIcon());
            campoCPF.setText("");
            JOptionPane.showMessageDialog(rootPane, "Cadastro excluido!");
        }
        else
        {
            campoPlaca.setText("");
            campoID.setText("");
            campoModelo.setText("");
            campoMarca.setText("");
            campoCor.setText("");
            jLabel1.setIcon(new ImageIcon());
            campoCPF.setText("");
            JOptionPane.showMessageDialog(rootPane, "Cadastro não excluido!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        campoPlaca.setText("");
            campoID.setText("");
            campoModelo.setText("");
            campoMarca.setText("");
            campoCor.setText("");
            jLabel1.setIcon(new ImageIcon());
            campoCPF.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        Veiculo veiculo = new Veiculo();
        String pl= campoPlaca.getText();
        Banco dao = new Banco();
        veiculo = dao.buscaVeiculo(pl);
        
        if(veiculo.getModelo() == null)
        {
            JOptionPane.showMessageDialog(rootPane, "Veículo não cadastrado!");
            campoPlaca.setText("");
        }
        else
        {
            campoID.setText(Integer.toString(veiculo.getIdveic()));
            campoModelo.setText(veiculo.getModelo());
            campoMarca.setText(veiculo.getMarca());
            campoCor.setText(veiculo.getCor());
            jLabel1.setIcon(new ImageIcon(veiculo.getImagem()));
            pl = dao.bCpf(veiculo.getIdprop());
            campoCPF.setText(pl);
            
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBuscar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JTextField campoCPF;
    private javax.swing.JTextField campoCor;
    private javax.swing.JTextField campoID;
    private javax.swing.JTextField campoMarca;
    private javax.swing.JTextField campoModelo;
    private javax.swing.JTextField campoPlaca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    // End of variables declaration//GEN-END:variables
}
