/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.Banco;
import dao.Multa;
import dao.Veiculo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paulo
 */
public class CadastroMulta extends javax.swing.JInternalFrame {

    /**
     * Creates new form CDM
     */
    public CadastroMulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoPlaca = new javax.swing.JTextField();
        campoID = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        campoDescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoData = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("Cadastro de multas");

        jLabel2.setText("Placa:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descrição", "Data"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Descrição:");

        jLabel4.setText("Data:");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jLabel1)
                            .addGap(185, 185, 185)
                            .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnBuscar))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel2)
                            .addGap(11, 11, 11)
                            .addComponent(campoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel3)
                            .addGap(0, 0, 0)
                            .addComponent(campoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel4)
                            .addGap(13, 13, 13)
                            .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btnCadastrar)
                            .addGap(9, 9, 9)
                            .addComponent(btnAlterar)
                            .addGap(5, 5, 5)
                            .addComponent(btnExcluir)
                            .addGap(7, 7, 7)
                            .addComponent(btnLimpar)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jLabel1))
                        .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar))
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(campoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(campoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCadastrar)
                        .addComponent(btnAlterar)
                        .addComponent(btnExcluir)
                        .addComponent(btnLimpar))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int linha = jTable1.getSelectedRow();
        campoID.setText(jTable1.getValueAt(linha,0).toString());
        campoDescricao.setText(jTable1.getValueAt(linha,1).toString());
        campoData.setText(jTable1.getValueAt(linha,2).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        Banco dao = new Banco();
        Veiculo veiculo = new Veiculo();
        String pl =campoPlaca.getText();
        veiculo = dao.buscaVeiculo(pl);
       
       
       if(veiculo.getIdveic()== 0)
       {
            JOptionPane.showMessageDialog(rootPane, "Placa inválida!");
           
       }
       else
       {
           String insert = "INSERT into cadmulta (idveic_multa, data_multa, descricao_multa) values ('"
            +veiculo.getIdveic()+"','"+campoData.getText()+"','"+campoDescricao.getText()+"')";
           if(dao.inserir(insert))
            {
                JOptionPane.showMessageDialog(rootPane, "Cadastro concluido com sucesso!");
                campoID.setText("");
                campoPlaca.setText("");
                campoData.setText("");
                campoDescricao.setText("");

            }
             else
             {
                 JOptionPane.showMessageDialog(rootPane, "Cadastro não enviado!");

              }  
            
       }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        
        Banco dao = new Banco();
        Veiculo veiculo = new Veiculo();
        String pl = campoPlaca.getText();
        veiculo = dao.buscaVeiculo(pl);
       
       
       if(veiculo.getIdveic()== 0)
       {
            JOptionPane.showMessageDialog(rootPane, "Placa inválida!");
           
       }
       else
       {
           String sql = "UPDATE cadmulta set  idveic_multa = '"
                +veiculo.getIdveic()+"',  data_multa ='"
                +campoData.getText()+"', descricao_multa = '"+campoDescricao.getText()+"' where id_multa = "
                +Integer.parseInt(campoID.getText());
           if(dao.inserir(sql))
            {
                tabela(Integer.parseInt(campoID.getText()));
                JOptionPane.showMessageDialog(rootPane, "Cadastro alterado com sucesso!");
                
                campoID.setText("");
                campoPlaca.setText("");
                campoData.setText("");
                campoDescricao.setText("");
                

            }
             else
             {
                 JOptionPane.showMessageDialog(rootPane, "Cadastro não enviado!");

             }  
            
       }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        Banco dao = new Banco();
        String sql= "DELETE from cadmulta where id_multa =" +Integer.parseInt(campoID.getText());
        if(dao.inserir(sql))
        {
            campoID.setText("");
            campoPlaca.setText("");
            campoData.setText("");
            campoDescricao.setText("");
            JOptionPane.showMessageDialog(rootPane, "Cadastro excluido com sucesso!");
            
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Não foi possivel excluir cadastro!");
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Banco dao = new Banco();
        Veiculo veiculo = new Veiculo();
        String pl=campoPlaca.getText();
        veiculo = dao.buscaVeiculo(pl);
        int idv =veiculo.getIdveic();
        try
        {
            tabela(idv);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Erro ao pesquisar!");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed
    public void tabela(int placa)
    {
        Banco dao = new Banco();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        
         if(placa!=0)
        {
            try{
                for(Multa p: dao.multa(placa)){

                    modelo.addRow(new Object[]{

                        p.getId_multa(),
                        p.getDesc_multa(),
                        p.getData()

                    });
                }
            }catch(Exception e )
            {
                JOptionPane.showMessageDialog(rootPane, "Veiculo não cadastrado!");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Veiculo não cadastrado!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JTextField campoData;
    private javax.swing.JTextField campoDescricao;
    private javax.swing.JTextField campoID;
    private javax.swing.JTextField campoPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
